# Generated by Django 3.2.7 on 2021-09-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=700)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
